server {
    listen 11436;
    listen [::]:11436;

    server_name _;

    client_max_body_size 100m;

    # Endpoint pubblico, senza token
    location = /api/version {
        proxy_pass http://127.0.0.1:11434;
        include snippets/ollama-proxy.conf;
    }

    # Tutti gli altri endpoint richiedono il token
    location / {
        include snippets/ollama-auth-check-w.conf;
        proxy_pass http://127.0.0.1:11434;
        include snippets/ollama-proxy.conf;
    }
}
